### ISSUE TITLE
Shape must be rank 0 but is rank 2

### ISSUE THREAD

**Issue by benjaminderei** [around1991/char2vec#1]
Hello,

I'm trying to use your code with wikipedia corpus and a gensim model with vector size 400.
I've modified the code inside word_segmenter.py to have a layer size of 400 (replacing all 256)
but i get a error in build line 95 of word_segmenter.py: 
ValueError: Shape must be rank 0 but is rank 2 for 'cond/Switch' (op: 'Switch') with input shapes: [?,?], [?,?].

What to do ?

Thx,
Ben.

**Comment by around1991** [comment]
Hi Ben

Can you post an exact stack trace please of where it goes wrong? I have a feeling that it's something to do with Tensorflow shape inference - I only tested it on Theano.

Kris

**Comment by benjaminderei** [comment]
Here it is :)
```
Traceback (most recent call last):
  File "train_char2vec.py", line 20, in <module>
    wordsegmenter.build(learn_context_weights=False)
  File "/Users/xxxxxxx/PycharmProjects/word2vecben/char2vec/word_segmenter.py", line 95, in build
    content_flat = attn([rnn_bidi, attention_2])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 172, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/layers/core.py", line 641, in call
    return self.function(x, **arguments)
  File "/Users/xxxxxxx/PycharmProjects/word2vecben/char2vec/word_segmenter.py", line 85, in attn_merge
    pre_softmax = K.switch(mask[0], logits, -numpy.inf)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2244, in switch
    else_expression_fn)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2213, in _cond
    return cond_fn(condition, then_lambda, else_lambda)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1748, in cond
    p_2, p_1 = switch(pred, pred)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 318, in switch
    return gen_control_flow_ops._switch(data, pred, name=name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/gen_control_flow_ops.py", line 371, in _switch
    result = _op_def_lib.apply_op("Switch", data=data, pred=pred, name=name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2397, in create_op
    set_shapes_for_outputs(ret)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 0 but is rank 2 for 'cond/Switch' (op: 'Switch') with input shapes: [?,?], [?,?].
```

**Comment by around1991** [comment]
Seems like it could be related to this issue: https://github.com/fchollet/keras/issues/2014

I don't really know what to suggest - I normally use Theano, where K.switch works fine. Maybe implement your own switch function which uses tf.cond, as suggested?

**Comment by benjaminderei** [comment]
I'm a beginner in the deep learning world so i have just switched to theano (it Work !)
thanx for the reply! i will look at it further later.
:)
